language: node_js
services: xvfb

jobs:
  include:
    - os: "osx"
      name: 'Unit tests: macOS/Chromium'
      node_js: "10.19.0"
      env:
        - CHROMIUM=true
      before_install:
        - PUPPETEER_PRODUCT=firefox npm install
      script:
        - ls .local-chromium .local-firefox
        - npm run tsc
        - npm run unit

    - os: "windows"
      name: 'Unit tests: Windows/Chromium'
      node_js: "10.19.0"
      env:
        - CHROMIUM=true
      before_install:
        - PUPPETEER_PRODUCT=firefox npm install
      script:
        - ls .local-chromium .local-firefox
        - npm run tsc
        - travis_retry npm run unit

    # Runs unit tests on Linux + Chromium
    - node_js: "10.19.0"
      name: 'Unit tests: Linux/Chromium'
      env:
        - CHROMIUM=true
      before_install:
        - PUPPETEER_PRODUCT=firefox npm install
      script:
        - npm run coverage

    # This bot runs all the extra checks that aren't the main Puppeteer unit tests
    - node_js: "10.19.0"
      name: 'Extra tests: Linux/Chromium'
      env:
        - CHROMIUM=true
      script:
        - npm run compare-protocol-d-ts
        - npm run test-install
        - npm run lint
        - npm run test-doclint
        - npm run test-types

    # Runs unit tests on Linux + Firefox
    - node_js: "10.19.0"
      name: 'Unit tests: Linux/Firefox'
      env:
        - FIREFOX=true
      before_install:
        - PUPPETEER_PRODUCT=firefox npm install
      script:
        - npm run funit

notifications:
  email: false
